# Only one instance of eureka service in this case
# we don't need to register eureka with other eureka services,
# or fetch other eureka instances
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost


#Port for eureka service
server:
  port: 8011
